Use explicit extension for require package.json
I got an error Error: Cannot find module "./package" when using webpack and setting `resolve.extensions = ['', '.js', '.jsx']`. As package here is not going to have another extension than .json I see no downside in this change.